name: "✨[简体中文] Valora 功能建议"
description: |
  感谢你为 Valora 提出的建议！我会在考量可行性后考虑是否加入该功能
title: "[Feature/简体中文]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: feature-type
    attributes:
      label: 请选择建议的方向
      options:
        - 网页外观
        - 新兴功能
        - 其他建议
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 请描述你的建议，如果有思维导图等示意图也可以附上
      placeholder: 请输入你的建议
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: 如果你能够提供一下联系到你的方式，我将会不胜感激；当然不填也是可以的！
      placeholder: 请填入联系方式
    validations:
      required: false