name: Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t vsc:$(date +%Y%m%d-%H%M%S) .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: |
          docker tag vsc:$(date +%Y%m%d-%H%M%S) vsc:latest
          docker push vsc:$(date +%Y%m%d-%H%M%S)
          docker push vsc:latest